#! /usr/bin/env bash

#
# Reattach to Tmux session.
#
# Reattach to a previously closed or detached terminal multiplexer session.
#
# Author:     Riccardo Finotello
# E-mail:     riccardo.finotello@gmail.com
#
# Copyright:  2020 - Riccardo Finotello
# License:    MIT License
#

# ------------------------------------
# OPTIONS, HELP, USAGE AND CHECKS
# ------------------------------------

# Show usage
function show_usage() {
    USAGE="$(basename $0) [-h] [-n] [-r]"
    printf "\n%s\n%s\n" "Usage:" "    $USAGE"
}

# Show help
function show_help() {
    show_usage
  
    printf "\n%s\n\n" "Reattach to Tmux session."
    printf "%s\n" "OPTIONS:"
    printf "%s\n" "    -h         Show this help and exit"
    printf "%s\n" "    -n         Open a new session"
    printf "%s\n" "    -r         Reattach to session"
  
    printf "\n%s\n%s\n\n" \
      "For bug report and info: riccardo.finotello@gmail.com" \
      "Copyright (c) 2020 - Riccardo Finotello - MIT License"
}

# Check if X11 menu is installed
[[ -x $(which dmenu) ]] || exit 1

# Check if Tmux is installed
[[ -x $(which tmux) ]] || exit 1

# Parse options
while getopts ":hnr" opt; do
    case $opt in
      h)
        show_help
        exit 0
        ;;
      \?)
        printf "%s\n" "Invalid option: -$OPTARG." >&2
        show_usage
        exit 1
        ;;
      n)
        $TERMINAL -e tmux -f $XDG_CONFIG_HOME/tmux/config -2
        exit 0
        ;;
      r)
        tmux list-sessions| grep -i -v 'attached'| \
              dmenu -i -l 20 -p 'Tmux detached sessions: '| \
              awk -F': ' '{print $1}'| \
              xargs -r -I{} $TERMINAL -e tmux attach-session -d -t {}
        exit 0
        ;;
      :)
        printf "%s\n" "-$OPTARG requires an argument." >&2
        show_usage
        exit 1
        ;;
    esac
done

# ------------------------------------
# COMMANDS AND INFO
# ------------------------------------
[[ -z $* ]] && (show_help && exit 1)
