#! /usr/bin/env bash

#
# Read battery info.
#
# This script reads battery information and displays it in the shortest possible
# form. It uses ACPI to get battery info and displays notifications in case
# the level drops below 10%.
#
# Author:     Riccardo Finotello
# E-mail:     riccardo.finotello@gmail.com
#
# Copyright:  2019 - Alessandra Cappati and Riccardo Finotello
# License:    MIT License
#

# ------------------------------------
# OPTIONS, HELP, USAGE AND CHECKS
# ------------------------------------

# Show usage
function show_usage() {
  USAGE="$(basename $0) [-h]"
  printf "\n%s\n%s\n" "Usage:" "    $USAGE"
}

# Show help
function show_help() {
  show_usage

  printf "\n%s\n\n" "Read battery info."
  printf "%s\n" "OPTIONS:"
  printf "%s\n" "    -h         Show this help and exit"

  printf "\n%s\n%s\n\n" \
    "For bug report and info: riccardo.finotello@gmail.com" \
    "Copyright (c) 2019 - Alessandra Cappati and Riccardo Finotello - MIT License"
}

# Parse options
while getopts ":h" opt; do
  case $opt in
    h)
      show_help
      exit 0
      ;;
    \?)
      printf "%s\n" "Invalid option: -$OPTARG." >&2
      show_usage
      exit 1
      ;;
    :)
      printf "%s\n" "-$OPTARG requires an argument." >&2
      show_usage
      exit 1
      ;;
  esac
done

# ------------------------------------
# COMMANDS AND INFO
# ------------------------------------

# Check the presence of UPOWER
if [[ ! -z $(which acpi) ]]; then
  INFO=$(which acpi)
else
  printf "%s\n%s\n%s\n" \
    "acpi is not in the PATH." \
    "You might have to add it. E.g.: sudo pacman -Syu acpi." \
    "acpi is a critical component: the script will not work without it." >&2
  exit 1
fi

# Check if the notification client is installed
if [[ ! -z $(which notify-send) ]]; then
  NOTIFICATIONS=$(which notify-send)
else
  printf "%s\n%s\n%s\n" \
    "The notification client is not in the PATH." \
    "You might have to add it. E.g.: sudo apt install ruby-notify." \
    "Some of the functionalities might be compromised." >&2
fi

# Read battery info
BATTERY="Battery 0"
BATTERYSTATUS=$($INFO -b | grep "$BATTERY" | awk -F ': ' '{print $2}' | tr -d ',')

STATUS=$(echo $BATTERYSTATUS | awk '{print $1}')
PERCENTAGE=$(echo $BATTERYSTATUS | awk '{gsub("%",""); print $2}')
TIME=$(echo $BATTERYSTATUS | awk '{print $3}')

if [[ $PERCENTAGE -gt 95 ]]; then
  case $STATUS in
    Discharging)
      ICON="\uf118 \uf240"
      ;;
    *)
      ICON="\uf118 \uf492"
      ;;
  esac
elif [[ $PERCENTAGE -gt 85 ]]; then
  case $STATUS in
    Discharging)
      ICON="\uf103 \uf240"
      ;;
    *)
      ICON="\uf102 \uf240"
      ;;
  esac
elif [[ $PERCENTAGE -gt 40 ]]; then
  case $STATUS in
    Discharging)
      ICON="\uf103 \uf242"
      ;;
    *)
      ICON="\uf102 \uf242"
      ;;
  esac
elif [[ $PERCENTAGE -gt 25 ]]; then
  case $STATUS in
    Discharging)
      ICON="\uf103 \uf244"
      ;;
    *)
      ICON="\uf102 \uf244"
      ;;
  esac
elif [[ $PERCENTAGE -gt 10 ]]; then
  case $STATUS in
    Discharging)
      ICON="\uf103 \uf60b"
      ;;
    *)
      ICON="\uf102 \uf60b"
      ;;
  esac
else
  case $STATUS in
    Discharging)
      ICON="\uf103 CAUTION!"
      ;;
    *)
      ICON="\uf102 CAUTION!"
      ;;
  esac
fi

echo -e "$PERCENTAGE% $ICON"

case $BLOCK_BUTTON in
  1)
    /usr/bin/pkill -RTMIN+1 i3blocks
    ;;
  2)
    /usr/bin/pkill -RTMIN+1 i3blocks
    ;;
  3)
    /usr/bin/pkill -RTMIN+1 i3blocks
    $NOTIFICATIONS -a "Battery" "Battery info" "Status: $STATUS\nCapacity: $PERCENTAGE%\nTime remaining: $TIME"
    ;;
esac

exit 0
