#! /usr/bin/env bash

#
# Toggle Wifi on and off and display connection info.
#
# The script toggles the connection capabilities on and off. It uses
# NetworkManager in order to get the current status of the interfaces and to
# toggle on and off both Wifi and Ethernet connection.
#
# Author:     Riccardo Finotello
# E-mail:     riccardo.finotello@gmail.com
#
# Copyright:  Alessandra Cappati and Riccardo Finotello - 2019
# License:    MIT License
#

# ------------------------------------
# OPTIONS, HELP, USAGE AND CHECKS
# ------------------------------------

# Show usage
function show_usage() {
  USAGE="$(basename $0) [-h] COMMAND"
  printf "\n%s\n%s\n" "Usage:" "    $USAGE"
}

# Show help
function show_help() {
  show_usage

  printf "\n%s\n\n" "Toggle Wifi on and off and display connection info."
  printf "%s\n" "OPTIONS:"
  printf "%s\n" "    -h         Show this help and exit"
  printf "\n%s\n" "COMMAND:"
  printf "%s\n" "    current    Show currently connected interface(s)"
  printf "%s\n" "    ip         Show IP of the connected interface(s)"
  printf "%s\n" "    toggle     Toggle Wifi interface on and off"

  printf "\n%s\n%s\n\n" \
    "For bug report and info: riccardo.finotello@gmail.com" \
    "Copyright (c) 2019 -  Alessandra Cappati and Riccardo Finotello - MIT License"
}

# Check if NetworkManager is installed
if [[ ! -z $(which nmcli) ]]; then
  NMCLI=$(which nmcli)
else
  printf "%s\n%s\n%s\n" \
    "The NetworkManager command line interface is not in the PATH." \
    "You might have to install it. E.g.: sudo apt install network-manager." \
    "The NetworkManager CLI is required for this script to run."
  exit 1
fi

# Parse options
while getopts ":h" opt; do
  case $opt in
    h)
      show_help
      exit 0
      ;;
    \?)
      printf "%s\n" "Invalid option: -$OPTARG." >&2
      show_usage
      exit 1
      ;;
    :)
      printf "%s\n" "-$OPTARG requires an argument." >&2
      show_usage
      exit 1
      ;;
  esac
done

# ------------------------------------
# COMMANDS AND INFO
# ------------------------------------

if [[ -z $1 ]]; then
  show_help
  exit 1
fi

# Show currently connected interface(s)
function get_wifi_info() {
  WIFIINFO=$($NMCLI -f IN-USE,SSID,SIGNAL -t dev wifi)
  WIFINAME=$(printf "%s\n" "$WIFIINFO"| awk -F ':' '/^[*]/ {print $2}')
  WIFISIGNAL=$(printf "%s\n" "$WIFIINFO"| awk -F ':' '/^[*]/ {print $3}')

  printf "%s (%s%%)\n" "$WIFINAME" "$WIFISIGNAL"
}

function show_current() {
  # Connected interfaces
  INTERFACES=$($NMCLI -f DEVICE,TYPE,STATE dev status | \
    awk '/\<connected\>/ {print $1, $2}')

  # Divide Wi-Fi and Ethernet interfaces
  ETHERNET=$(printf "%s\n" "$INTERFACES" | awk '/\<ethernet\>/ {print $1}')
  WIFI=$(printf "%s\n" "$INTERFACES" | awk '/\<wifi\>/ {print $1}')

  # Print output
  if [[ ! -z $WIFI ]] && [[ ! -z $ETHERNET ]]; then
    echo -e "\uf1eb $(get_wifi_info)\n\uf6ff Ethernet"
  elif [[ ! -z $WIFI ]] && [[ -z $ETHERNET ]]; then
    echo -e "\uf1eb $(get_wifi_info)"
  elif [[ -z $WIFI ]] && [[ ! -z $ETHERNET ]]; then
    echo -e "\uf6ff Ethernet"
  else
    echo -e "\ufaa9 No connection"
  fi
}

# Show current IP address
function show_ip() {
  # Connected interfaces
  INTERFACES=$($NMCLI -f DEVICE,TYPE,STATE dev status | \
    awk '/\<connected\>/ {print $1, $2}')

  # Divide Wi-Fi and Ethernet interfaces
  ETHERNET=$(printf "%s\n" "$INTERFACES" | awk '/\<ethernet\>/ {print $1}')
  WIFI=$(printf "%s\n" "$INTERFACES" | awk '/\<wifi\>/ {print $1}')

  # Get IP info
  if [[ ! -z $(which ip ) ]]; then
    INFO="$(which ip) addr show"
  elif [[ ! -z $(which ifconfig) ]]; then
    INFO=$(which ifconfig)
  else
    printf "%s\n" \
      "Unable to show IP address at this time."
    exit 1
  fi

  WIFIIP=$($INFO $WIFI | awk '/\<inet\>/ {gsub("/.*",""); print $2}')
  ETHERNETIP=$($INFO $ETHERNET | awk '/\<inet\>/ {gsub("/.*",""); print $2}')

  # Print output
  if [[ ! -z $WIFI ]] && [[ ! -z $ETHERNET ]]; then
    echo -e "\uf1eb $WIFIIP\n\uf6ff $ETHERNETIP"
  elif [[ ! -z $WIFI ]] && [[ -z $ETHERNET ]]; then
    echo -e "\uf1eb $WIFIIP"
  elif [[ -z $WIFI ]] && [[ ! -z $ETHERNET ]]; then
    echo -e "\uf6ff $ETHERNETIP"
  else
    echo -e "\ufaa9 No connection"
  fi
}

# Toggle Wifi interface on and off
function toggle_wifi_state() {
  STATUS=$($NMCLI radio wifi)

  if [[ $STATUS = "enabled" ]]; then
    $NMCLI radio wifi off
  else
    $NMCLI radio wifi on
  fi
}

# Parse commands
case $1 in
  current)
    show_current
    exit 0
    ;;
  ip)
    show_ip
    exit 0
    ;;
  toggle)
    toggle_wifi_state
    exit 0
    ;;
  *)
    printf "%s\n" "Invalid COMMAND: $1 is not a valid argument."
    show_help
    exit 1
    ;;
esac


# Check if the notification client is installed
if [[ ! -z $(which notify-send) ]]; then
  NOTIFICATIONS=$(which notify-send)
else
  printf "%s\n%s\n%s\n" \
    "The notification client is not in the PATH." \
    "You might have to install it. E.g.: sudo apt install ruby-notify." \
    "Some of the functionalities of this script may be compromised otherwise."
fi

# Clickable block when using i3blocks in i3wm
function show_notification() {
  ICON="/usr/share/icons/gnome/48x48/status/network-idle.png"
  if [[ -f $ICON  ]]; then
    NOTIFICATIONS="$NOTIFICATIONS --icon $ICON"
  fi
  
  $NOTIFICATIONS --category=network "Connection manager" "$($NMCLI -p device $1)"
}

case $BLOCK_BUTTON in
  1)
    show_notification status
    exit 0
    ;;
  2)
    /usr/bin/pkill -RTMIN+1 i3blocks
    exit 0
    ;;
  3)
    show_notification wifi
    exit 0
    ;;
esac
