#! /usr/bin/env bash

#
# Open bookmarks.
#
# Read bookmarks list and open links in a browser window.
#
# Author:     Riccardo Finotello
# E-mail:     riccardo.finotello@gmail.com
#
# Copyright:  2020 - Riccardo Finotello
# License:    MIT License
#

# ------------------------------------
# OPTIONS, HELP, USAGE AND CHECKS
# ------------------------------------

# Show usage
function show_usage() {
    USAGE="$(basename $0) [-h] [-e] [-m]"
    printf "\n%s\n%s\n" "Usage:" "    $USAGE"
}

# Show help
function show_help() {
    show_usage
  
    printf "\n%s\n\n" "Open bookmarked URLs."
    printf "%s\n" "OPTIONS:"
    printf "%s\n" "    -h         Show this help and exit"
    printf "%s\n" "    -e         Edit the bookmark file"
    printf "%s\n" "    -m         Open selection menu"
  
    printf "\n%s\n%s\n\n" \
      "For bug report and info: riccardo.finotello@gmail.com" \
      "Copyright (c) 2020 - Riccardo Finotello - MIT License"
}

# Check if the X11 menu is installed
[[ -x $(which dmenu) ]] || exit 1

# Check if browser is set
[[ -n $BROWSER ]] && URLOPEN=$BROWSER || URLOPEN=xdg-open

# Choose the bookmarks list
LIST=$XDG_DATA_HOME/dbookmarks/bookmarks.txt
[[ ! -f $LIST ]] && (mkdir -p $XDG_DATA_HOME/dbookmarks 2> /dev/null \
                     && touch $LIST)

# Parse options
while getopts ":hem" opt; do
    case $opt in
      h)
        show_help
        exit 0
        ;;
      e)
        [[ $EDITOR ]] && $EDITOR $LIST || xdg-open $LIST
        exit 0
        ;;
      m)
        cat $LIST| sort| column -t -s'^^^'| \
            dmenu -i -l 20 -p 'Web bookmarks: '| awk '{print $NF}'| \
            xargs -r $BROWSER
        exit 0
        ;;
      \?)
        printf "%s\n" "Invalid option: -$OPTARG." >&2
        show_usage
        exit 1
        ;;
      :)
        printf "%s\n" "-$OPTARG requires an argument." >&2
        show_usage
        exit 1
        ;;
    esac
done

# vim: ft=sh
