#! /usr/bin/env bash

#
# Select and display man page.
#
# Search and select for a man page and display it as PDF.
#
# Author:     Riccardo Finotello
# E-mail:     riccardo.finotello@gmail.com
#
# Copyright:  2020 - Riccardo Finotello
# License:    MIT License
#

# ------------------------------------
# OPTIONS, HELP, USAGE AND CHECKS
# ------------------------------------

# Show usage
function show_usage() {
    USAGE="$(basename $0) [-h]"
    printf "\n%s\n%s\n" "Usage:" "    $USAGE"
}

# Show help
function show_help() {
    show_usage
  
    printf "\n%s\n\n" "Select and display man page."
    printf "%s\n" "OPTIONS:"
    printf "%s\n" "    -h         Show this help and exit"
  
    printf "\n%s\n%s\n\n" \
      "For bug report and info: riccardo.finotello@gmail.com" \
      "Copyright (c) 2020 - Riccardo Finotello - MIT License"
}

# Parse options
while getopts ":h" opt; do
    case $opt in
      h)
        show_help
        exit 0
        ;;
      \?)
        printf "%s\n" "Invalid option: -$OPTARG." >&2
        show_usage
        exit 1
        ;;
      :)
        printf "%s\n" "-$OPTARG requires an argument." >&2
        show_usage
        exit 1
        ;;
    esac
done

# Check if dmenu/rofi are installed
[[ -x $(which dmenu) ]] && XMENU=dmenu || exit 1

# Check if a PDF reader is installed
[[ $READER ]] && PDFOPEN=$READER || PDFOPEN=xdg-open

# ------------------------------------
# COMMANDS AND INFO
# ------------------------------------
MANPAGE=$(apropos .| sort| sed 's/[)] *- /)^^^/'| column -t -s'^^^'| \
          $XMENU -i -l 20 -p 'Man pages: '| awk '{print $1}')

[[ $MANPAGE ]] && (man -Tpdf $MANPAGE| $READER -) || exit 1

exit 0

# vim: ft=sh
