#! /usr/bin/env bash

#
# Open files.
#
# Open a file from a dropdown menu.
#
# Author:     Riccardo Finotello
# E-mail:     riccardo.finotello@gmail.com
#
# Copyright:  2020 - Riccardo Finotello
# License:    MIT License
#

# ------------------------------------
# OPTIONS, HELP, USAGE AND CHECKS
# ------------------------------------

# Show usage
function show_usage() {
    USAGE="$(basename $0) [-h]"
    printf "\n%s\n%s\n" "Usage:" "    $USAGE"
}

# Show help
function show_help() {
    show_usage

    printf "\n%s\n\n" "Open files."
    printf "%s\n" "OPTIONS:"
    printf "%s\n" "    -h         Show this help and exit"

    printf "\n%s\n%s\n\n" \
           "For bug report and info: riccardo.finotello@gmail.com" \
           "Copyright (c) 2020 - Riccardo Finotello - MIT License"
}

# Check if X11 menu is installed
[[ -x $(which dmenu) ]] && XMENU=dmenu || exit 1

# Parse options
while getopts ":h" opt; do
    case $opt in
      h)
          show_help
          exit 0
          ;;
      \?)
          printf "%s\n" "Invalid option: -$OPTARG." >&2
          show_usage
          exit 1
          ;;
      :)
          printf "%s\n" "-$OPTARG requires an argument." >&2
          show_usage
          exit 1
          ;;
    esac
done

# ------------------------------------
# COMMANDS AND INFO
# ------------------------------------
find $HOME -maxdepth 1 -mindepth 1 -not -path "*/[@.]*" -type d| sort| \
    $XMENU -i -l 20| \
    xargs -r -I{} find {} -maxdepth 1 -not -path "*/[@.]*" -type d| sort| \
    $XMENU -i -l 20| \
    xargs -r -I{} find {} -not -path "*/[@.]*" -type f| sort| \
    $XMENU -i -l 20| \
    xargs -r xdg-open

exit 0

# vim: ft=sh
