#! /usr/bin/env bash

#
# Current keyboard layout.
#
# The scripts reads and displays the current keyboard layout.
#
# Author:     Riccardo Finotello
# E-mail:     riccardo.finotello@gmail.com
#
# Copyright:  2020 - Riccardo Finotello
# License:    MIT License
#

# ------------------------------------
# OPTIONS, HELP, USAGE AND CHECKS
# ------------------------------------

# Show usage
function show_usage() {
  USAGE="$(basename $0) [-h] [-s] [-l] [-c]"
  printf "\n%s\n%s\n" "Usage:" "    $USAGE"
}

# Show help
function show_help() {
  show_usage

  printf "\n%s\n\n" "Display current layout"
  printf "%s\n" "OPTIONS:"
  printf "%s\n" "    -h    Show this help and exit"
  printf "%s\n" "    -s    Short version"
  printf "%s\n" "    -l    Long version"
  printf "%s\n" "    -c    Change layout"

  printf "\n%s\n%s\n\n" \
    "For bug report and info: riccardo.finotello@gmail.com" \
    "Copyright (c) 2020 - Riccardo Finotello - MIT License"
}

# Check if xkblayout-state is installed
[[ -x $(which xkblayout-state) ]] && XKB=xkblayout-state || exit 1

# Clickable widget
function clickable_widget() {
  case $BLOCK_BUTTON in
    1)
      pkill -RTMIN+1 i3blocks
      $XKB set +1
      ;;
    2)
      pkill -RTMIN+1 i3blocks
      ;;
    3)
      notify-send \
          "Input Layout" \
          "Current: $($XKB print %n)\nAvailable: $($XKB print %N| xargs)"
      pkill -RTMIN+1 i3blocks
      ;;
  esac
}

# Parse options
while getopts ":hslc" opt; do
  case $opt in
    h)
      show_help
      exit 0
      ;;
    s)
      echo -e "\uf024 $($XKB print %s)"
      clickable_widget
      exit 0
      ;;
    l)
      echo -e "\uf024 $($XKB print %n)"
      exit 0
      ;;
    c)
      $XKB set +1
      echo -e "New layout: $($XKB print %n)"
      exit 0
      ;;
    \?)
      printf "%s\n" "Invalid option: -$OPTARG." >&2
      show_usage
      exit 1
      ;;
    :)
      printf "%s\n" "-$OPTARG requires an argument." >&2
      show_usage
      exit 1
      ;;
  esac
done

# ------------------------------------
# COMMANDS AND INFO
# ------------------------------------
[[ -z $* ]] && (show_help && exit 1)

# vim: ft=sh
