#! /usr/bin/env bash

#
# Read screen temperature.
#
# This script is a companion to the "redshift" applet. It reads the screen
# temperature and the period of the day and outputs very brief information.
#
# Author:     Riccardo Finotello
# E-mail:     riccardo.finotello@gmail.com
#
# Copyright:  2020 - Riccardo Finotello
# License:    MIT License
#

# ------------------------------------
# OPTIONS, HELP, USAGE AND CHECKS
# ------------------------------------

# Show usage
function show_usage() {
  USAGE="$(basename $0) [-h]"
  printf "\n%s\n%s\n" "Usage:" "    $USAGE"
}

# Show help
function show_help() {
  show_usage

  printf "\n%s\n\n" "Read screen temperature."
  printf "%s\n" "OPTIONS:"
  printf "%s\n" "    -h         Show this help and exit"

  printf "\n%s\n%s\n\n" \
    "For bug report and info: riccardo.finotello@gmail.com" \
    "Copyright (c) 2020 - Riccardo Finotello - MIT License"
}

# Check if Redsihft is installed
[[ -x $(which redshift) ]] || exit 1

# Parse options
while getopts ":h" opt; do
  case $opt in
    h)
      show_help
      exit 0
      ;;
    \?)
      printf "%s\n" "Invalid option: -$OPTARG." >&2
      show_usage
      exit 1
      ;;
    :)
      printf "%s\n" "-$OPTARG requires an argument." >&2
      show_usage
      exit 1
      ;;
  esac
done

# ------------------------------------
# COMMANDS AND INFO
# ------------------------------------
# Read screen temperature
PERIOD=$(redshift -p 2> /dev/null| awk '/^Period/ {print $NF}')
TEMPERATURE=$(redshift -p 2> /dev/null| awk '/^Colour/ {print $NF}')

[[ $PERIOD == 'Daytime' ]] \
    && echo -e "\uf185 $TEMPERATURE" \
    || echo -e "\uf186 $TEMPERATURE"

# Clickable widget
case $BLOCK_BUTTON in
  3)
    pkill -RTMIN+1 i3blocks
    notify-send \
    -a "Screen Temperature" \
    -i "display-brightness-symbolic.symbolic" \
    "Screen Colour Temperature" \
    "$(redshift -p 2> /dev/null)"
    ;;
esac

exit 0
